###아이템 가져오기
GET http://localhost:8080/api/item

###아이템 가져오기
GET http://localhost:8080/api/item/1


###아이템 생성
POST http://localhost:8080/api/item
Content-Type: application/json

{
  "name": "test name",
  "description": "test description",
  "propertyList": [
    {
      "itemPropertyType": "SIZE",
      "content": "XL"
    },
    {
      "itemPropertyType": "PRICE",
      "content": "1,000원"
    }
  ],
  "tagList": [
    "test1",
    "test2"
  ]
}

###아이템 포스팅
POST http://localhost:8080/api/item/1/post
Content-Type: application/json

{
  "imageList": [
    "img1",
    "img2"
  ],
  "content": "test content"
}
